using System.Text;
using IoTSpy.Api.Services;
using IoTSpy.Core.Interfaces;
using IoTSpy.Core.Models;
using IoTSpy.Proxy.Interception;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IoTSpy.Api.Controllers;

[ApiController]
[Authorize(Roles = "admin")]
[Route("api/admin/firewall")]
public class FirewallController(
    IProxySettingsRepository proxySettingsRepo,
    IWindowsFirewallHelper firewallHelper,
    IPlatformInfo platformInfo,
    IAuditRepository auditRepo) : ControllerBase
{
    private static readonly FirewallRule[] FixedRules =
    [
        new(5000, "TCP", "API (HTTP)"),
        new(5001, "TCP", "API (HTTPS)"),
        new(MqttBrokerSettingsDefaultPort, "TCP", "MQTT broker proxy"),
        new(CoapProxySettingsDefaultPort, "UDP", "CoAP proxy"),
    ];

    // MqttBrokerSettings/CoapProxySettings aren't persisted anywhere (ProtocolProxyController
    // takes them per-request on start) — use their documented model defaults here.
    private const int MqttBrokerSettingsDefaultPort = 1883;
    private const int CoapProxySettingsDefaultPort = 5683;

    private async Task<IReadOnlyList<FirewallRule>> GetCurrentRulesAsync(CancellationToken ct)
    {
        var proxySettings = await proxySettingsRepo.GetAsync(ct);
        var rules = new List<FirewallRule>(FixedRules)
        {
            new(proxySettings.ProxyPort, "TCP", "Explicit HTTP(S) proxy"),
            new(proxySettings.TransparentProxyPort, "TCP", "Transparent proxy"),
        };
        return rules;
    }

    [HttpGet("script")]
    public async Task<IActionResult> GetScript([FromQuery] string platform = "windows", CancellationToken ct = default)
    {
        if (!string.Equals(platform, "windows", StringComparison.OrdinalIgnoreCase))
            return StatusCode(501, new { error = $"Firewall script generation for '{platform}' is not yet supported. Windows is the only supported platform in this version." });

        var rules = await GetCurrentRulesAsync(ct);
        var script = BuildPowerShellScript(rules);
        return File(Encoding.UTF8.GetBytes(script), "application/octet-stream", "iotspy-configure-firewall.ps1");
    }

    private static string BuildPowerShellScript(IReadOnlyList<FirewallRule> rules)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# IoTSpy firewall setup script");
        sb.AppendLine($"# Generated by IoTSpy on {DateTimeOffset.UtcNow:u}");
        sb.AppendLine("# Opens inbound Windows Defender Firewall rules for IoTSpy's listening ports.");
        sb.AppendLine("# Run this script from an elevated (Administrator) PowerShell prompt.");
        sb.AppendLine();
        foreach (var rule in rules)
        {
            sb.AppendLine($"netsh advfirewall firewall add rule name=\"IoTSpy - {rule.Label}\" dir=in action=allow protocol={rule.Protocol} localport={rule.Port}");
        }
        return sb.ToString();
    }

    public record ConfigureFirewallDto(string Platform = "windows");
    public record ConfigureFirewallResponse(IReadOnlyList<FirewallRuleResult> Results, bool OverallSuccess);

    [HttpPost("configure")]
    public async Task<IActionResult> Configure([FromBody] ConfigureFirewallDto? dto, CancellationToken ct)
    {
        if (!platformInfo.IsWindows)
        {
            return StatusCode(501, new { error = "Automatic firewall configuration is only supported on Windows in this version. Use the downloadable script for other platforms." });
        }

        var rules = await GetCurrentRulesAsync(ct);
        var results = await firewallHelper.ConfigureRulesAsync(rules);
        var overallSuccess = results.All(r => r.Success);

        await auditRepo.AddAsync(new AuditEntry
        {
            Username = User.Identity?.Name ?? "system",
            Action = "FirewallRulesConfigured",
            EntityType = "FirewallRule",
            Details = $"{results.Count(r => r.Success)}/{results.Count} rules applied: " +
                      string.Join(", ", results.Select(r => $"{r.Label} ({r.Protocol}/{r.Port})={(r.Success ? "OK" : r.Message)}")),
            IpAddress = HttpContext.Connection.RemoteIpAddress?.ToString() ?? ""
        }, ct);

        return Ok(new ConfigureFirewallResponse(results, overallSuccess));
    }
}
